/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasiarisan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.GridLayout;
import java.awt.BorderLayout;       
import java.util.ArrayList;         
import java.util.List;           
import java.util.Random;          
import javax.swing.Timer;           
import javax.swing.JDialog;         
import javax.swing.JOptionPane;     



/**
 *
 * @author teddy
 */
public class MainFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
    initComponents();
        this.setSize(1200, 500);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(java.awt.Color.decode("#F5F5DC"));
        jLabel1.setForeground(java.awt.Color.decode("#161E54"));
        jLabel2.setForeground(java.awt.Color.decode("#161E54"));
        txtNama.setBackground(java.awt.Color.decode("#FFFFFF"));
        txtNama.setForeground(java.awt.Color.decode("#161E54"));
        txtTelepon.setBackground(java.awt.Color.decode("#FFFFFF"));
        txtTelepon.setForeground(java.awt.Color.decode("#161E54"));
        lblGrandTotal.setForeground(java.awt.Color.decode("#161E54"));
        tblPeserta.setBackground(java.awt.Color.decode("#FFFFFF"));
        tblPeserta.setForeground(java.awt.Color.decode("#161E54"));
        btnSimpan.setBackground(java.awt.Color.decode("#06923E"));
        btnHapus.setBackground(java.awt.Color.decode("#DD0303"));
        btnHapus.setForeground(java.awt.Color.decode("#161E54"));
        btnResetSetoran.setBackground(java.awt.Color.decode("#FFEB00"));
        btnResetSetoran.setForeground(java.awt.Color.decode("#161E54"));
        btnReset.setBackground(java.awt.Color.decode("#FFEB00"));
        btnReset.setForeground(java.awt.Color.decode("#161E54"));
        btnKocok.setBackground(java.awt.Color.decode("#9BEC00"));
        btnKocok.setForeground(java.awt.Color.decode("#161E54"));
        btnAdmin.setBackground(java.awt.Color.decode("#5800FF"));
        tblPeserta.getTableHeader().setReorderingAllowed(false);
        tblPeserta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tampilkanData();
}
    
    private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("No");
    model.addColumn("Nama Peserta");
    model.addColumn("No Telp");
    String[] bulan = {"Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des"};
    for (String b : bulan) model.addColumn(b);
    model.addColumn("Total Setoran");
    model.addColumn("Status");
    
    int totalUangSekampung = 0;

    try {
        java.sql.Connection c = Koneksi.getKoneksi();
        java.sql.ResultSet rs = c.createStatement().executeQuery("SELECT * FROM peserta");
        int no = 1;

        while(rs.next()) {
            int totalPerOrang = 0;
            Object[] row = new Object[18]; // 18 kolom
            row[0] = rs.getInt("id");
            row[1] = no++;
            row[2] = rs.getString("nama");
            row[3] = rs.getString("no_telp");
            
            // Isi data b1 - b12 ke tabel
            for(int i = 1; i <= 12; i++) {
                int bayar = rs.getInt("b" + i);
                row[i + 3] = bayar; // Mulai dari index ke-3 di tabel
                totalPerOrang += bayar;
            }
            
            row[16] = "Rp " + totalPerOrang;
            row[17] = rs.getInt("status_menang") == 0 ? "Belum" : "MENANG 🎉";
            totalUangSekampung += totalPerOrang;
            model.addRow(row);
        }
        tblPeserta.setModel(model);
        java.text.NumberFormat nf = java.text.NumberFormat.getInstance(new java.util.Locale("id", "ID"));
        lblGrandTotal.setText("Total Uang: Rp " + nf.format(totalUangSekampung));
        
        // Sembunyiin ID
        tblPeserta.getColumnModel().getColumn(0).setMinWidth(0);
        tblPeserta.getColumnModel().getColumn(0).setMaxWidth(0);
        
    } catch (Exception e) { System.out.println(e.getMessage()); }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeserta = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAdmin = new javax.swing.JButton();
        btnKocok = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblGrandTotal = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnResetSetoran = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arisan Bersama");

        jLabel1.setText("Nama Peserta");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tblPeserta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        tblPeserta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesertaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPeserta);

        jPanel1.setBackground(new java.awt.Color(222, 222, 209));

        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnKocok.setText("Mulai Kocok");
        btnKocok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKocokActionPerformed(evt);
            }
        });

        btnReset.setText("Reset Pemenang");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKocok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKocok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        lblGrandTotal.setText("jLabel2");

        jLabel2.setText("No. Telepon");

        btnHapus.setText("Hapus Peserta");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnResetSetoran.setText("Reset Setoran");
        btnResetSetoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetSetoranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(btnResetSetoran))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnSimpan)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblGrandTotal))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnResetSetoran))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnHapus)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nama = txtNama.getText();
        String telp = txtTelepon.getText();
    
    if(nama.isEmpty()|| telp.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Nama dan No Telp jangan kosong!");
        return;
    }

    try {
        java.sql.Connection c = Koneksi.getKoneksi(); 
        
        java.sql.PreparedStatement cek = c.prepareStatement("SELECT id FROM peserta WHERE nama = ? OR no_telp = ?");
        cek.setString(1, nama);
        cek.setString(2, telp);
        java.sql.ResultSet rs = cek.executeQuery();
        
        if (rs.next()) {
            // 2. Kalau ADA, maka UPDATE
            int idLama = rs.getInt("id");
            java.sql.PreparedStatement update = c.prepareStatement("UPDATE peserta SET nama = ?, no_telp = ? WHERE id = ?");
            update.setString(1, nama);
            update.setString(2, telp);
            update.setInt(3, idLama);
            update.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Data Peserta di-Update, Bos!");
        } else {
            // 3. Kalau TIDAK ADA, maka INSERT baru
            java.sql.PreparedStatement insert = c.prepareStatement("INSERT INTO peserta (nama, no_telp) VALUES (?, ?)");
            insert.setString(1, nama);
            insert.setString(2, telp);
            insert.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Peserta Baru Ditambahkan!");
        }
        
        tampilkanData();
        txtNama.setText("");
        txtTelepon.setText("");
    } catch (Exception e) {
        System.out.println("Gagal simpan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
    String passDb = "";
    try {
        java.sql.ResultSet rs = Koneksi.getKoneksi().createStatement().executeQuery("SELECT password FROM admin WHERE username='admin'");
        if(rs.next()) passDb = rs.getString("password");
    } catch(Exception e) {}

    javax.swing.JDialog adminDialog = new javax.swing.JDialog(this, "Panel Admin", true);
    adminDialog.setLayout(new java.awt.GridLayout(3, 1, 10, 10));
    
    adminDialog.add(new javax.swing.JLabel("  Username: admin", javax.swing.SwingConstants.LEFT));
    adminDialog.add(new javax.swing.JLabel("  Password: " + passDb, javax.swing.SwingConstants.LEFT));
    
    javax.swing.JPanel panelTombol = new javax.swing.JPanel();
    javax.swing.JButton btnTutup = new javax.swing.JButton("Tutup");
    javax.swing.JButton btnGanti = new javax.swing.JButton("Ganti Password");
    panelTombol.add(btnTutup);
    panelTombol.add(btnGanti);
    adminDialog.add(panelTombol);

    // Event Tutup
    btnTutup.addActionListener(e -> adminDialog.dispose());

    // Event Ganti Password (Popup Lagi)
    btnGanti.addActionListener(e -> {
        adminDialog.dispose();
        tampilPopupGantiPassword();
    });

    adminDialog.setSize(300, 200);
    adminDialog.setLocationRelativeTo(this);
    adminDialog.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void tampilPopupGantiPassword() {
    javax.swing.JDialog gantiDialog = new javax.swing.JDialog(this, "Ubah Password", true);
    gantiDialog.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

    javax.swing.JPasswordField txtLama = new javax.swing.JPasswordField();
    javax.swing.JPasswordField txtBaru = new javax.swing.JPasswordField();
    javax.swing.JPasswordField txtUlangi = new javax.swing.JPasswordField();
    javax.swing.JButton btnUbah = new javax.swing.JButton("Ubah");

    gantiDialog.add(new javax.swing.JLabel(" Password Lama:")); gantiDialog.add(txtLama);
    gantiDialog.add(new javax.swing.JLabel(" Password Baru:")); gantiDialog.add(txtBaru);
    gantiDialog.add(new javax.swing.JLabel(" Ulangi Password:")); gantiDialog.add(txtUlangi);
    gantiDialog.add(new javax.swing.JLabel("")); gantiDialog.add(btnUbah);

    btnUbah.addActionListener(e -> {
        String lama = new String(txtLama.getPassword());
        String baru = new String(txtBaru.getPassword());
        String ulang = new String(txtUlangi.getPassword());

        try {
            java.sql.Connection c = Koneksi.getKoneksi();
            // Cek password lama bener gak
            java.sql.ResultSet rs = c.createStatement().executeQuery("SELECT password FROM admin WHERE username='admin'");
            if(rs.next() && rs.getString("password").equals(lama)) {
                if(baru.equals(ulang)) {
                    java.sql.PreparedStatement p = c.prepareStatement("UPDATE admin SET password=? WHERE username='admin'");
                    p.setString(1, baru);
                    p.executeUpdate();
                    JOptionPane.showMessageDialog(gantiDialog, "Password Berhasil Diubah!");
                    gantiDialog.dispose();
                } else {
                    JOptionPane.showMessageDialog(gantiDialog, "Password baru nggak cocok, Bos!");
                }
            } else {
                JOptionPane.showMessageDialog(gantiDialog, "Password lama salah!");
            }
        } catch(Exception ex) { System.out.println(ex.getMessage()); }
    });

    gantiDialog.setSize(350, 200);
    gantiDialog.setLocationRelativeTo(this);
    gantiDialog.setVisible(true);
}
    
    private void btnKocokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKocokActionPerformed
        try {
        java.sql.Connection c = Koneksi.getKoneksi();
        java.sql.ResultSet rs = c.createStatement().executeQuery("SELECT nama FROM peserta WHERE status_menang = 0");
        java.util.ArrayList<String> listNama = new java.util.ArrayList<>();
        while(rs.next()) listNama.add(rs.getString("nama"));

        if(listNama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gak ada kandidat, Bos!");
            return;
        }

        // Munculin Roda
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "RODA ARISAN", true);
        PanelRoda roda = new PanelRoda(listNama);
        dialog.add(roda);
        dialog.pack();
        dialog.setLocationRelativeTo(this);

        // Timer Animasi Putar
        javax.swing.Timer timer = new javax.swing.Timer(20, null);
        final double[] speed = {20.0 + new java.util.Random().nextDouble() * 20};
        final double[] currentAngle = {0};

        timer.addActionListener(e -> {
            currentAngle[0] += speed[0];
            roda.setSudut(currentAngle[0]);
            speed[0] *= 0.97; // Efek gesekan (melambat)

            if (speed[0] < 0.5) {
                timer.stop();
                // Hitung siapa yang ditunjuk jarum (0 derajat di atas)
                double finalAngle = (360 - (currentAngle[0] % 360) + 90) % 360;
                int indexWinner = (int) (finalAngle / (360.0 / listNama.size())) % listNama.size();
                String pemenang = listNama.get(indexWinner);
                
                javax.swing.JOptionPane.showMessageDialog(dialog, "Selamat! " + pemenang + " Menang!");
                
                // Update DB
                try {
                    c.createStatement().executeUpdate("UPDATE peserta SET status_menang = 1 WHERE nama = '" + pemenang + "'");
                    tampilkanData();
                } catch(Exception ex) {}
                dialog.dispose();
            }
        });

        timer.start();
        dialog.setVisible(true);

    } catch (Exception e) {}
    }//GEN-LAST:event_btnKocokActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin mau reset semua status menang?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
if (confirm == javax.swing.JOptionPane.YES_OPTION) {
    try {
        java.sql.Connection c = Koneksi.getKoneksi();
        java.sql.PreparedStatement p = c.prepareStatement("UPDATE peserta SET status_menang = 0");
        p.executeUpdate();
        tampilkanData();
        javax.swing.JOptionPane.showMessageDialog(this, "Status di-reset! Semua bisa ikut kocokan lagi.");
    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
}
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblPesertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesertaMouseClicked
       int baris = tblPeserta.getSelectedRow();
    int kolom = tblPeserta.getSelectedColumn();
    
    // Cek kalau yang diklik adalah kolom bulan (Januari - Desember ada di index 3 sampe 14)
    if (kolom >= 4 && kolom <= 15) {
        String id = tblPeserta.getValueAt(baris, 0).toString();
        String namaBulan = tblPeserta.getColumnName(kolom);
        
        // Pilihan buat Bos
        Object[] options = {"50,000", "100,000", "Ketik Sendiri", "Batal"};
        int n = JOptionPane.showOptionDialog(this,
            "Pilih Setoran " + namaBulan + " buat " + tblPeserta.getValueAt(baris, 2),
            "Input Setoran",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null, options, options[2]);

        String jumlah = "0";
        if (n == 0) jumlah = "50000";
        else if (n == 1) jumlah = "100000";
        else if (n == 2) jumlah = JOptionPane.showInputDialog("Masukkan angka:");
        else return;

        try {
            java.sql.Connection c = Koneksi.getKoneksi();
            // Kolom di DB kan b1, b2... sedangkan kolom di tabel Jan=3, Feb=4
            int indexBulan = kolom - 3; 
            String sql = "UPDATE peserta SET b" + indexBulan + " = ? WHERE id = ?";
            java.sql.PreparedStatement p = c.prepareStatement(sql);
            p.setInt(1, Integer.parseInt(jumlah));
            p.setInt(2, Integer.parseInt(id));
            p.executeUpdate();
            
            tampilkanData();
        } catch (Exception e) { JOptionPane.showMessageDialog(this, "Input salah, Bos!"); }
    }
    }//GEN-LAST:event_tblPesertaMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int baris = tblPeserta.getSelectedRow();
if (baris == -1) {
    JOptionPane.showMessageDialog(this, "Pilih dulu orangnya di tabel, Bos!");
    return;
}

// Ambil ID dari kolom pertama (index 0)
String id = tblPeserta.getValueAt(baris, 0).toString();
String nama = tblPeserta.getValueAt(baris, 1).toString();

int confirm = JOptionPane.showConfirmDialog(this, "Yakin mau hapus si " + nama + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

if (confirm == JOptionPane.YES_OPTION) {
    try {
        java.sql.Connection c = Koneksi.getKoneksi();
        String sql = "DELETE FROM peserta WHERE id = ?";
        java.sql.PreparedStatement p = c.prepareStatement(sql);
        p.setInt(1, Integer.parseInt(id));
        p.executeUpdate();

        JOptionPane.showMessageDialog(this, "Udah di-kick, Bos!");
        tampilkanData(); // Refresh tabel
    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetSetoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetSetoranActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Bos, yakin mau nol-kan SEMUA setoran dari Januari - Desember?", 
            "Konfirmasi Reset Setoran", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection c = Koneksi.getKoneksi();
            // Kita set b1 sampe b12 jadi 0 semua dalam satu perintah SQL
            String sql = "UPDATE peserta SET "
                       + "b1=0, b2=0, b3=0, b4=0, b5=0, b6=0, "
                       + "b7=0, b8=0, b9=0, b10=0, b11=0, b12=0";
            
            java.sql.PreparedStatement p = c.prepareStatement(sql);
            p.executeUpdate();

            // Panggil fungsi tampilkanData biar tabel & label total uang langsung update jadi Rp 0
            tampilkanData();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Setoran berhasil diputihkan, Bos! Mulai dari nol ya.");
        } catch (Exception e) {
            System.out.println("Gagal reset setoran: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnResetSetoranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKocok;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResetSetoran;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JTable tblPeserta;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
